// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXP2unq8uZqUJiJk2fVjV0u_bQKXo6jNg',
    appId: '1:1087250356574:web:42819b06c386855fd797cf',
    messagingSenderId: '1087250356574',
    projectId: 'finaltodoapp-bf947',
    authDomain: 'finaltodoapp-bf947.firebaseapp.com',
    storageBucket: 'finaltodoapp-bf947.firebasestorage.app',
    measurementId: 'G-ZSYL0VN6RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpjSmv6zHlcMqThdbp9SsNmxIBGXC8nwI',
    appId: '1:1087250356574:android:4c63bc873eacedb1d797cf',
    messagingSenderId: '1087250356574',
    projectId: 'finaltodoapp-bf947',
    storageBucket: 'finaltodoapp-bf947.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFgYszwfHvrM_SnQ1aomL4QzjLteKw51s',
    appId: '1:1087250356574:ios:92c1b37ad4beb9f6d797cf',
    messagingSenderId: '1087250356574',
    projectId: 'finaltodoapp-bf947',
    storageBucket: 'finaltodoapp-bf947.firebasestorage.app',
    iosBundleId: 'com.example.finaltodoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFgYszwfHvrM_SnQ1aomL4QzjLteKw51s',
    appId: '1:1087250356574:ios:92c1b37ad4beb9f6d797cf',
    messagingSenderId: '1087250356574',
    projectId: 'finaltodoapp-bf947',
    storageBucket: 'finaltodoapp-bf947.firebasestorage.app',
    iosBundleId: 'com.example.finaltodoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXP2unq8uZqUJiJk2fVjV0u_bQKXo6jNg',
    appId: '1:1087250356574:web:629ee3e409273271d797cf',
    messagingSenderId: '1087250356574',
    projectId: 'finaltodoapp-bf947',
    authDomain: 'finaltodoapp-bf947.firebaseapp.com',
    storageBucket: 'finaltodoapp-bf947.firebasestorage.app',
    measurementId: 'G-F9FYDPTN9G',
  );
}
